BAU: Update to use latest version of common-test-utils library
common-test-utils library is using latest version of mockito-core and is compatible with Java 11.
Remove org.mockito:mockito-core:1.9.5 as this library is too old.
Update all unit tests to use org.mockito.junit.MockitoJUnitRunner instead of org.mockito.runners.MockitoJUnitRunner since org.mockito.runners.MockitoJUnitRunner is deprecated.
Replace org.mockito.Matchers.* with org.mockito.ArgumentMatchers.* since org.mockito.Matchers.* is deprecated.
Resolve UnnecessaryStubbingException in unit tests.
Refactor ResponseSignatureCreatorTest to get rid of duplicate code and NullPointerException and make it easy to read.
Add jaxb library to resolve NoClassDefFoundError raised in
EidasTrustAnchorResolverTest.

Author: @adityapahuja